### ISSUE TITLE
Missing info about OpenGB server start

### ISSUE THREAD

**Issue by jog1t** [rivet-gg/opengb#427]
@kacper said:

> Missing info about started server. As a new user, I don't know if the OpenGB started or not, and on which port.

**Comment by NathanFlurry** [comment]
@kacper do you mean how to start a server or when a server has started?

as of the latest version, it logs this:

<img src="https://uploads.linear.app/296b26dd-14fd-4d1f-aa10-714d93154ee5/722c5290-d459-4f0b-9a65-c4cda4ee79b9/4ac607cf-0ff7-41d8-9a85-086b26a870c0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI5NmIyNmRkLTE0ZmQtNGQxZi1hYTEwLTcxNGQ5MzE1NGVlNS83MjJjNTI5MC1kNDU5LTRmMGItOWE2NS1jNGNkYTRlZTc5YjkvNGFjNjA3Y2YtMGZmNy00MWQ4LTlhODUtMDg2YjI2YTg3MGMwIiwiaWF0IjoxNzIwMDgyODQ3LCJleHAiOjMzMjkwNjQyODQ3fQ.lAS4lQzOz5KW5a5zqgKzhlf-S3CaVdTLFFOPvLmNzEo " alt="image.png" width="635" height="372" />
